In [ ]:
import pandas as pd

df_repu = pd.read_csv(
    "../data/interim/df_repu.csv", low_memory=False, dtype={"ID_orateur": str}
)
df_annot = pd.read_csv(
    "../data/interim/annotations_republique-test-base_default_train.csv",
    low_memory=False,
    dtype={"ID_orateur": str},
)

In [ ]:
df_joined = df_repu.merge(
    df_annot,
    left_on="ID_paragraphe",
    right_on="dataset_ID_paragraphe",
    how="left",
    suffixes=("_repu", "_annot"),
)
df_joined.head()

,UID,SeanceRef,SessionRef,DateSeance,DateSeanceJour,NumSeanceJour,NumSeance,TypeAssemblee,Legislature,Session,...,Texte_clean,repu_match_valide,Unnamed: 0,id,dataset_ID_paragraphe,text,default,user,timestamp,comment
0,CRSANR5L16S2023O1N173,RUANR5L16S2023IDS26877,SCR5A2023O1,20230313160000000,lundi 13 mars 2023,1,173,AN,16,Session ordinaire 2022-2023,...,Certains de nos partenaires européens affichen...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CRSANR5L16S2023O1N173,RUANR5L16S2023IDS26877,SCR5A2023O1,20230313160000000,lundi 13 mars 2023,1,173,AN,16,Session ordinaire 2022-2023,...,"Il y a un peu plus d’un an, le discours de Bel...",True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CRSANR5L16S2023O1N173,RUANR5L16S2023IDS26877,SCR5A2023O1,20230313160000000,lundi 13 mars 2023,1,173,AN,16,Session ordinaire 2022-2023,...,Le groupe Rassemblement national ne cachera pa...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CRSANR5L16S2023O1N173,RUANR5L16S2023IDS26877,SCR5A2023O1,20230313160000000,lundi 13 mars 2023,1,173,AN,16,Session ordinaire 2022-2023,...,"Ce que l’on veut nous imposer, c’est à la fois...",True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CRSANR5L16S2023O1N173,RUANR5L16S2023IDS26877,SCR5A2023O1,20230313160000000,lundi 13 mars 2023,1,173,AN,16,Session ordinaire 2022-2023,...,"Je souhaite intervenir contre cet amendement, ...",True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_joined = df_joined.drop(
    columns=[
        "Unnamed: 0",
        "id",
        "dataset_ID_paragraphe",
        "text",
        "user",
        "timestamp",
        "comment",
    ]
)

In [ ]:
df_joined = df_joined.rename(columns={"default": "previous_annotation"})

In [ ]:
import csv

df_joined.to_csv(
    "../data/interim/df_first_annotation.csv", index=False, quoting=csv.QUOTE_ALL
)

In [ ]:
df_joined["previous_annotation"].value_counts(dropna=False)

previous_annotation
NaN           3788
Republique     152
Autre           18
Name: count, dtype: int64